const mockData = [
    {
        id: 1,
        name: "iPhone 15 Pro",
        price: 4,
        image: require('./images/iPhone.png'),
        category: "Телефон",
    },
    {
        id: 2,
        name: "iPhone 16",
        price: 5,
        image: require('./images/iPhone16.png'),
        category: "Телефон",
    },
    {
        id: 3,
        name: "PS 5 аренда",
        price: 18,
        image: require('./images/ps5_2.png'),
        category: "Игровая приставка",
    },
    {
        id: 4,
        name: "Nokia 7A",
        price: 3,
        image: require('./images/nokia7a.png'),
        category: "Телефон",
    },
    {
        id: 5,
        name: "Sony Camera",
        price: 25,
        image: require('./images/camera_sony.png'),
        category: "Камера",
    },
    {
        id: 6,
        name: "Samsung Galaxy 9",
        price: 4,
        image: require('./images/galaxy9.png'),
        category: "Телефон",
    },
    {
        id: 7,
        name: "iPhone 16",
        price: 5,
        image: require('./images/iPhone16.png'),
        category: "Телефон",
    },
    {
        id: 8,
        name: "PS 5",
        price: 20,
        image: require('./images/ps5.png'),
        category: "Игровая приставка",
    },
    {
        id: 9,
        name: "Camera Canon",
        price: 24,
        image: require('./images/camera_canon.png'),
        category: "Камера",
    },
    {
        id: 10,
        name: "Nokia 7A",
        price: 3,
        image: require('./images/nokia7a.png'),
        category: "Телефон",
    },
    {
        id: 11,
        name: "Camera Instax",
        price: 15,
        image: require('./images/camera_instax.png'),
        category: "Камера",
    },
    {
        id: 12,
        name: "ps5",
        price: 22,
        image: require('./images/ps5_3.png'),
        category: "Игровая приставка",
    },
    {
        id: 13,
        name: "Samsung Galaxy 9",
        price: 4,
        image: require('./images/galaxy9.png'),
        category: "Телефон",
    },
    {
        id: 14,
        name: "iPhone 16",
        price: 5,
        image: require('./images/iPhone16.png'),
        category: "Телефон",
    },
]

export default mockData;
